import type { Metadata } from "next";
import "./globals.css";
import { LocaleProvider } from "@/components/providers/locale-provider";
import { LayoutWithLocale } from "@/components/providers/layout-with-locale";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <LocaleProvider>
      <LayoutWithLocale>{children}</LayoutWithLocale>
    </LocaleProvider>
  );
}
